### ISSUE TITLE
OneAreaStatus body type

### ISSUE THREAD

**Issue by terafin** [thenewwazoo/lutron-leap-js#11]
```
2022-01-31T02:36:21.602Z leap:message:bodytype parsing body type OneAreaStatus with data: {
  AreaStatus: {
    href: '/area/729/status',
    Level: 100,
    OccupancyStatus: 'Occupied',
    CurrentScene: { href: '/areascene/734' }
  }
}

```

Note, works for sub too:
            leap.subscribe('/area/status', function(subscribeResponse) { // works for subscribe!
                logging.info('area subscribe response: ' + subscribeResponse)
            }, 'SubscribeRequest')

**Comment by terafin** [comment]
Done, PR will come.

**Comment by thenewwazoo** [comment]
I'm reviewing this as I work on the Caséta occupancy sensor support, and I'd really love to get this knowledge encapsulated in an `RA3Processor` class that would provide methods to abstract away subscribing to this or that.

**Comment by terafin** [comment]
Makes sense! I have a Caseta and a ra3 setup that I’m in process of expanding. I’ll try to separate this… note: it might make sense to focus on LEAP versions instead of products, but only time will tell

**Comment by thenewwazoo** [comment]
Possibly! Because I happen to have it in front of me, my Caséta Smart Bridge 2 running firmware 8.7 reports LEAPVersion 1.114.

**Comment by terafin** [comment]
RA3 is reporting Leap 3.14 (checking)

**Comment by terafin** [comment]
@thenewwazoo Correction: LEAPVersion:3.215

**Comment by thenewwazoo** [comment]
Does that come from a ping response? e.g.
```{'CommuniqueType': 'ReadResponse', 'Header': {'MessageBodyType': 'OnePingResponse', 'StatusCode': '200 OK', 'Url': '/server/1/status/ping'}, 'Body': {'PingResponse': {'LEAPVersion': 1.114}}}```

**Comment by terafin** [comment]
Yup.

[2022-02-02T21:46:54.494] [INFO] logger - command: [/server/1/status/ping]()     result: {"Header":{"MessageBodyType":"OnePingResponse","StatusCode":{"message":"OK","code":200},"Url":"[/server/1/status/ping]()","ClientTag":"68fc68f9-58af-4c09-ac79-f62b471b5f12"},"CommuniqueType":"ReadResponse","Body":{"PingResponse":{"LEAPVersion":3.215}}}

**Comment by thenewwazoo** [comment]
I wonder if RA2 devices report LEAP version 2.something.
