### ISSUE TITLE
Has this been tested with RadioRA3 Sunnata Dimmers and Keypads?

### ISSUE THREAD

**Issue by mbelkin** [thenewwazoo/lutron-leap-js#16]
I saw a recent commit about RA3 but wanted to be sure before pulling the trigger on ordering a system. Thanks!

**Comment by thenewwazoo** [comment]
@terafin graciously added the RA3 code, so they’ll have to answer to what extent it’s been tested with the RA3. I only have a Caséta system (but if you want to order two… 😅)

**Comment by terafin** [comment]
@mbelkin I can confirm it does work on RA3, I've tested with a Sunnata Dimmer, Sunnata switch, a wall motion sensor, and  a ceiling mounted one... I'm just about to pull the trigger on a larger system once I get the whole house done in the designer.

I'm sure there's stuff to fix, and document, but... I can confirm I do have this working, and am using this to bridge into my system here:
https://github.com/terafin/mqtt-lutron-leap-bridge

**Comment by thenewwazoo** [comment]
There you go! Thank you, @terafin!
