### ISSUE TITLE
Support new Homeworks QSX LEAP varient

### ISSUE THREAD

**Issue by JJTech0130** [thenewwazoo/lutron-leap-js#17]
There is a new (I think beta) way of using the leap protocol. I have a rudimentary implementation in my https://github.com/JJTech0130/llfp repository, but I would like to integrate it into this one.
Instead of requiring certs, you need to send a log in packet with a username/password.
You use with a TLS socket on port 8081.
I will try and implement here when I get some time.

**Comment by JJTech0130** [comment]
Here are the documents I have:
[040458a_Preliminary.pdf](https://github.com/thenewwazoo/lutron-leap-js/files/8054584/040458a_Preliminary.pdf)
~~[LEAP protocol - 1.120 - Phoenix.pdf]()~~
Note that I don't think they include the login packet.
**EDIT:**
*What the heck is going on with edits Github...*
```python
def login(self, id, password):
        packet = {
            "CommuniqueType": "UpdateRequest",
            "Header": {
                "Url": "/login"
            },
            "Body": {
                "Login": {
                    "ContextType": "Application",
                    "LoginID": id,
                    "Password": password
                }
            }
        }

        return self._leap.send(packet)
```
I have removed the 1.120 document.

**Comment by thenewwazoo** [comment]
Hi @JJTech0130, I opened the first of those documents and saw that the first page is marked Lutron Confidential. Unfortunately, I'm concerned that reading it will taint this codebase, as it's otherwise an unencumbered implementation based on reverse-engineering and other open-source codebases. Can you help me understand the origin of these documents?

**Comment by JJTech0130** [comment]
I got them from someone I know who works there, because I have a beta system in my house. I didn't know if I wasn't supposed to share them. Do you want me to remove them?
Anyway, the protocol is mostly the same I think, just with that login packet rather than certs. The login packet I got by asking the person, as it's not it the docs that I saw.

**Comment by JJTech0130** [comment]
I see that the 1.120 version is marked confidential, however the preliminary (newer) version I don't see it. Don't know if that means anything...
I thought the release checkbox meant that it was released to the public somewhere... maybe I misunderstood that.

**Comment by thenewwazoo** [comment]
Sorry for being a stickler, I just don't know Lutron's disposition for third-party implementations, and I don't want to risk them asserting copyright over anything in this repo.

With that said, in order to establish the TLS connection with a Caseta bridge, you have to present the bridge-signed certificate. If that's not established, there's no way to send the LEAP packet. Is this login packet in addition to the mutual cert auth? If so, it seems simple to add a method to do it.

**Comment by JJTech0130** [comment]
This device, which I think is a HomeWorks QSX, but I'm not entirely sure, uses the username/password configured to login with the packet, instead of the traditional certificate based authentication.

**Comment by JJTech0130** [comment]
So the things that need changed that I can see so far:
+ make `handleDiscovery` accept a systype of `HWQSProcessor`
+ send login packet
+ walk area tree for devices, as `/device` returns "204 No Content"
+ use `/server/status/ping` instead of `/server/1/status/ping`

**Comment by thenewwazoo** [comment]
Ah, word. I think a new class alongside SmartBridge for the processor would be the way to go. The ping method would also need to get pulled out of LeapClient, since it's coupled to the device and not the protocol.

**Comment by JJTech0130** [comment]
Yes. Though I'm not sure if that's really necessary for now- even if ping returns an error, is that enough to keep the connection alive?

EDIT:
Wouldn't this be a more helpful way of writing the handleDiscovery thing?
The old error was rather unspecific.
```ts
        if (svc.data.get('systype') === 'SmartBridge') {
            // return a SmartBridge
        } else if (svc.data.get('systype') === 'HWQSProcessor') {
            // return a HWQSProcessor
        } else {
            // throw an error
            logDebug('unknown system type', svc.data.get('systype'));
            throw new Error('unknown system type');
        }
```

**Comment by thenewwazoo** [comment]
This library was originally written specifically for my Caseta plugin for Homebridge, so it's not very general in its design. In fact, I didn't know there _were_ other devices that spoke LEAP. 😁

As regards LeapClient and BridgeFinder, I have a very strong desire to keep them strictly constrained to _only_ those parts that are shared, if the whole library is to be extended to encompass more device types (which I'd love!). That is, any logic that is not shared should be contained in the device's class. It means a bit more refactoring (c.f. first para), but imo it'd be worth it.

**Comment by JJTech0130** [comment]
Yeah, I'd eventually refactor that. I just want to get a working implementation first, though!

**Comment by JJTech0130** [comment]
Ah, so I got some basic things working, however, I just realized that Caseta (and most of Homebridge) works off of the concept of "Devices",  whereas HomeWorks focuses on "Zones", which may contain multiple devices. This means more work for me. Also, I need to make it parse areas in order to be able to find zones, as you can only walk the tree, not get them all at once (as there may be a *ton* of zones, meant for huge installations).

**Comment by JJTech0130** [comment]
I might just fake it for now, and shim the zones as devices. (and hardcode their hrefs)

**Comment by thenewwazoo** [comment]
That's roughly the approach @johninaustin [ended up taking](https://github.com/gurumitts/pylutron-caseta/issues/80#issuecomment-1032229694) (at least in an initial pass, I haven't been following closely). I'm pretty lukewarm about the idea, to be honest. I'd prefer this repo be a reflect of LEAP as it is in reality, and let consumers add abstractions as they choose. I'm excited that you're making progress, though.

**Comment by JJTech0130** [comment]
I’m just trying to get it to work as quickly as possible, then I’ll come back as I have time an polish it up. I agree that it isn’t the best approach, but I really just to use it :).
Eventually, it would be great to make everything fully supported though!

**Comment by JJTech0130** [comment]
Also apparently HWQSX _can_ use certs, which lets you use secret parts of the protocol not documented in the docs I have... it's apparently caseta certs with a special addition? Anyway, not really important as most things can be done without, and I don't even know how you'd discover the secret endpoints let alone use them.

**Comment by thenewwazoo** [comment]
Interesting. Write down what you know here so it doesn’t get lost and I’ll see if I can follow the trail :)

**Comment by JJTech0130** [comment]
Unfortunately, they didn't mention much else . It's apparently used by their app (and possibly the designer?) for adding devices and the like, so if someone could get ahold of that they could probably figure some things out. Idk if the app was publicly released yet, I don't have it myself.

**Comment by JJTech0130** [comment]
This app https://play.google.com/store/apps/details?id=com.lutron.mmw&hl=en might work, not sure.

**Comment by JJTech0130** [comment]
You said "reverse engineering" earlier... does that mean it's OK to decompile that app with JADX/Apktool? Or is that endangering the nature of this project too? Sorry if that's a stupid question, I don't really understand the nuances of these things...

**Comment by thenewwazoo** [comment]
No, it's a totally reasonable question. I'm concerned that anything that contains _logic_ could be considered a "derivative work", but am okay with implementing _interfaces_ (which I consider object definitions and URLs to be part of, per Google vs Oracle). I've personally decompiled things for those two purposes, but stay away from anything that looks workflow-like (request-response-request-response chains, etc). LEAP is pretty consistent, so following hunches tends to work pretty well. I'm not an attorney, and I don't know how litigious Lutron is, so I'm just trying to play it safe.

**Comment by thenewwazoo** [comment]
All that being said, [this APK](https://play.google.com/store/apps/details?id=com.lutron.lutronconnect&hl=en) might prove more useful.

**Comment by JJTech0130** [comment]
Idk, the HWQSX page linked to the other one:

https://www.lutron.com/TechnicalDocumentLibrary/048782.pdf

**Comment by JJTech0130** [comment]
Wait, so are some devices not implemented anywhere, eg. for lights?
EDIT:
+ I'm just now realizing that `lutron-leap-js` just implements the basic protocol, and the homebridge plugin does most of the work. Would you be interested in moving some of the abstractions into this? It seems like that would make it easier to use this library for other applications.
+ Another thing, perhaps it would be more idiomatic to define the message types beside, or at least close to, where they are used, rather than lumping them all together into one file? (Only if the above point is accepted, obviously)

**Comment by JJTech0130** [comment]
Here's the kind of structure I was thinking:
![image](https://user-images.githubusercontent.com/53275876/154598514-fcf498a3-b6a8-4781-84ef-662e83b5b885.png)

**Comment by thenewwazoo** [comment]
I don't think I quite see a need to add a device-level abstraction that's distinct from whatever a consumer of the library would build. That is to say, LEAP messages themselves fairly cleanly represent their constituent Lutron devices (at least, in the Caséta case). My Homebridge plugin therefore represents HomeKit devices that are updated by consuming updates about those LEAP devices. I dunno, I'm having a hard time imagining what I'd write that wouldn't duplicate functionality. I admit that could be a failure of imagination on my part. :)

I still like the idea of keeping this library focused on LEAP, and leaving the "but what does it _mean_?" questions to be answered elsewhere.

**Comment by JJTech0130** [comment]
Ah ok. Well perhaps another library in between, or completely separate? I was hoping for something that I could integrate into an app without having to duplicate what you wrote for the plug-in.
Just making sure I understand this right, do you not expose lights to HomeKit? I couldn't find them...

**Comment by thenewwazoo** [comment]
Yeah so far I’ve only implemented things that aren’t natively supported in HomeKit by the caseta bridge.

**Comment by JJTech0130** [comment]
It would be cool if this could be used for custom automation, separate from HomeKit. That’s why I thought it would be nice to integrate more than just the protocol, so it would be a ready made solution. Perhaps that would be better as a separate library on top of this. 🤔

**Comment by thenewwazoo** [comment]
I'm refactoring the BridgeFinder class right now to pull the bridge construction and secret handling logic out of it. Basically, it's going to find anything that answers to _tcp._lutron, and return its systype alongside the IP and serial number. I need this for bridge pairing, and I think decoupling them would enable adding other bridge types (handled in other libraries).

**Comment by thenewwazoo** [comment]
Okay, v3 of this library landed. Check it out. I'm curious to know what the BridgeFinder class finds on your network.

**Comment by JJTech0130** [comment]
(Sorry about not responding... I've been really busy with schoolwork.)
I'll try to test it this week.

**Comment by unawaremutual** [comment]
Hi all im a qsx programmer and have a system available to test and debug with. What is the best system to set up to utilize this library with?

**Comment by thenewwazoo** [comment]
I’m not quite sure I understand the question. I’ve run this library on Raspbian and macOS, but anything with a node runtime can run it.

**Comment by thenewwazoo** [comment]
I'd still love to have a way to validate the behavior of this library against non-Caséta bridges, but unless/until I get my hands on one, there's not much I can do. Since I've added a section to the README discussing building abstractions based on this library, I'm going to close this up. Please reopen if I've misunderstood and there's more to be done.
