### ISSUE TITLE
OneZoneDefinition body type

### ISSUE THREAD

**Issue by terafin** [thenewwazoo/lutron-leap-js#2]
```
2022-01-31T00:48:27.601Z leap:message:bodytype parsing body type OneZoneDefinition with data: {
  Zone: {
    href: '/zone/622',
    Name: 'Loft Outdoors',
    ControlType: 'Switched',
    Category: { Type: 'OtherAmbient', IsLight: true },
    AssociatedArea: { href: '/area/729' },
    SortOrder: 0
  }
}
```

**Comment by thenewwazoo** [comment]
Thanks for the new info! I can't promise I'll be able to add them soon, but if you look at [this commit](https://github.com/thenewwazoo/lutron-leap-js/commit/0eaeeac217cc0fbe160a466ccdbf97083b607e18), you can look at MessageBodyTypes.ts and the related tests to see how to add new types. It's pretty simple. Then it's "just" a question of wiring up whatever behaviours you need. :)

**Comment by terafin** [comment]
Will start some commits once I troll through everything with this RA3 box. Side question, I'm trying to get subscribes working, and `/occupancygroup/status` doesn't seem supported on RA3, any other thoughts about which paths one might subscribe to for device updates?

**Comment by terafin** [comment]
Found it!

            leap.subscribe('/zone/status', function(subscribeResponse) {
                logging.info('zone subscribe response: ' + subscribeResponse)
            }, 'SubscribeRequest')

**Comment by terafin** [comment]
@thenewwazoo I am also not a typescript programmer, I can easily drop these in, but - any primer how to compile/test it?

**Comment by terafin** [comment]
I think I got building working.. now to test...

**Comment by thenewwazoo** [comment]
If you're interested in occupancy information, check [the tracking ticket](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap/issues/18) over there. Caséta won't let you subscribe to individual occupancygroups (e.g. `/occupancygroup/1/status`), you have to have a singleton subscribe to `/occupancygroup/status` and handle updates (or route the update). I'd be interested to know if RA3 lets you subscribe to individual occupancygroups.

**Comment by thenewwazoo** [comment]
Also, uh, sorry about the state of the tests. 😂

**Comment by terafin** [comment]
> If you're interested in occupancy information, check [the tracking ticket](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap/issues/18) over there. Caséta won't let you subscribe to individual occupancygroups (e.g. `/occupancygroup/1/status`), you have to have a singleton subscribe to `/occupancygroup/status` and handle updates (or route the update). I'd be interested to know if RA3 lets you subscribe to individual occupancygroups.

They don't seem to be showing up *at all* 

I had to get it working this way: https://github.com/thenewwazoo/lutron-leap-js/issues/11

**Comment by terafin** [comment]
(Note to self: Done, just doing them all for a single PR)
