### ISSUE TITLE
Control devices?

### ISSUE THREAD

**Issue by sergei202** [thenewwazoo/lutron-leap-js#23]
First off, thank you for the awesome library!  Exactly what I was looking for!

One thing that I didn't see in here is an ability to control lights/dimmers?

I checked out the sister project, https://github.com/thenewwazoo/homebridge-lutron-caseta-leap,
and it mentions that light/dimmer support is already inside of HomeKit so it's not needed in this library?
Unfortunately, I'm not using HomeKit, so I'm going to have to create that from scratch.

If you could point me in right direction to add output support, I would be very appreciative!

**Comment by thenewwazoo** [comment]
Hi @sergei202, this project is only an implementation of the protocol, which doesn't have a concept of a device as such. I wrote [a bit about it in the readme](https://github.com/thenewwazoo/lutron-leap-js#device-support). This library is what you would use to communicate in order to control a dimmer, but the logic to do that would live elsewhere. It might be worth looking around to see if there are any other users of this library that could be inspiration.

**Comment by sergei202** [comment]
For anyone who arrives here looking for the same thing, it's actually very easy to control devices:

Get your device object from `bridge.getDeviceInfo()`, it'll look something like this:
```
  {
    Name: 'Cans',
    DeviceType: 'WallDimmer',
    AssociatedArea: { href: '/area/5' },
    href: '/device/11',
    SerialNumber: 64668928,
    FullyQualifiedName: [ 'Office', 'Cans'],
    Parent: { href: '/project' },
    ModelNumber: 'PD-6WCL-XX',
    LocalZones: [ { href: '/zone/8' } ],
    LinkNodes: [ { href: '/device/11/linknode/11' } ],
    DeviceRules: [ { href: '/devicerule/27' } ],
    AddressedState: 'Addressed'
  }
```

Then pass the `LocalZones[0].href` to `client.request()`:
```
client.request('CreateRequest', '/zone/8/commandprocessor',
    {'Command':{'CommandType':'GoToLevel','Parameter':[{'Type':'Level','Value':50}]}}
).then(r => console.log('response=%o', r));
```

**Comment by thenewwazoo** [comment]
Thank you for documenting that! I've been chewing on it, and I think having a separate abstraction for physical devices, as a place to encode the kind of logic you've written here, is probably a good idea. Given that a few different devices use similar commands, I even think a device-command-protocol MVC-ish style approach would allow a clean implementation.
